grant execute on st to public;
grant execute on nt to public;
grant execute on n to public;
grant execute on tmp to public;
grant execute on r to public;
grant execute on ra to public;
grant execute on rb to public;
grant execute on u to public;
grant execute on e to public;
grant execute on g to public;
grant execute on k_http to public -- h;
grant execute on k_xhtp to public -- p;
grant execute on k_type_tool to public -- t;
grant execute on k_gw to public;
grant execute on k_bg to public;
grant execute on k_filter to public;
grant all on ext_url_v to public;
grant execute on k_debug to public -- odb;
grant execute on k_sess to public -- s;
grant execute on kv to public;
grant execute on rs to public;
grant execute on k_ext_call to public -- dco;
grant execute on pdu to public;
grant execute on k_gac to public -- gac;
